version: "3.4"
volumes:
  postgres_data:
services:
    elasticsearch:
        build:
            context: ./
            dockerfile: ./docker/elasticsearch/Dockerfile
        ports:
            - "9200:9200"
            - "9300:9300"
    postgres:
        image: postgres:10.3
        restart: always
        volumes:
          - postgres_data:/var/lib/postgresql/data/
          - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
        environment:
            POSTGRES_USER: cfpb
            POSTGRES_PASSWORD: cfpb
            POSTGRES_DB: cfgov
            #    python2:
            #        volumes:
            #            - ./:/src/cfgov-refresh
            #            - ./develop-apps:/src/develop-apps
            #        ports:
            #            - "8000:8000"
            #        environment:
            #            DATABASE_URL: "postgresql://cfpb:cfpb@postgres/cfgov"
            #            ES_HOST: elasticsearch
            #            PYTHON: /usr/bin/python2
            #        depends_on:
            #            - elasticsearch
            #            - postgres
            #        stdin_open: true
            #        tty: true
            #        # see also: docker-compose.override.yml, which will be processed by default
            #        # https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
    python3:
        build: 
            context: ./
            dockerfile: ./Dockerfile
            target: cfgov-deployment
        image: cfgov-deployment
        ports:
            - "8333:8000"
        environment:
            ES_HOST: elasticsearch
            DATABASE_URL: "postgresql://cfpb:cfpb@postgres/cfgov"
        depends_on:
            - elasticsearch
            - postgres
        stdin_open: true
        tty: true
